---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  postgres
  database: yak
  username: maiha
  password: 
  host:     localhost

  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  postgresql
  #     database: sample_development
  #     username: the_user
  #     password: secrets
  #     host:     localhost
  #   repo2:
  #     ...

test:
  <<:       *defaults
  database: sample_test

  # repositories:
  #   repo1:
  #     database: sample_development

production:
  <<:       *defaults
  database: hpma2008

  # repositories:
  #   repo1:
  #     database: sample_development

rake:
  <<: *defaults
